name: Anemo CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'Android.bp'
      - '/metadata'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'Android.bp'
      - '/metadata'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Signing key
        if: ${{ github.event_name == 'push' }}
        run: |
          echo 'androidStorePassword=${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo 'androidKeyAlias=${{ secrets.ALIAS }}' >> local.properties
          echo 'androidKeyPassword=${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo 'androidStoreFile=sign_key.p12' >> local.properties
          echo '${{ secrets.KEY_STORE }}' | base64 --decode > temp_sign_key.jks
          # Convert JKS to PKCS12 format to avoid compatibility issues
          keytool -importkeystore \
            -srckeystore temp_sign_key.jks \
            -srcstoretype JKS \
            -srcstorepass '${{ secrets.KEY_STORE_PASSWORD }}' \
            -destkeystore sign_key.p12 \
            -deststoretype PKCS12 \
            -deststorepass '${{ secrets.KEY_STORE_PASSWORD }}' \
            -srcalias '${{ secrets.ALIAS }}' \
            -destalias '${{ secrets.ALIAS }}' \
            -srckeypass '${{ secrets.KEY_PASSWORD }}' \
            -destkeypass '${{ secrets.KEY_PASSWORD }}' \
            -noprompt
          rm temp_sign_key.jks
      - name: Build
        id: build
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :app:assembleDebug
      - name: Upload artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: app.apk
          path: "app/build/outputs/apk/debug/app-debug.apk"
          retention-days: 14
